version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - api/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # remove in production
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/BeMotivated
        - ME_CONFIG_BASICAUTH_USERNAME=root
        - ME_CONFIG_BASICAUTH_PASSWORD=password
    links:
        - mongodb
    restart: unless-stopped
    ports:
        - 8081:8081

  api:
    build:
        context: .
        target: development
        dockerfile: api/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - api/.env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
